# Generated by Django 3.1.12 on 2023-03-11 08:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_colleges'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='college',
            field=models.CharField(default=datetime.datetime(2023, 3, 11, 8, 19, 30, 632297, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='colleges',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='colleges',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='colleges',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='colleges',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='colleges',
            name='uniqid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='desc',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='header',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='organizer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='tag',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
