# Generated by Django 3.1.12 on 2023-03-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20230311_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='id',
            field=models.UUIDField(default=1, primary_key=True, serialize=False),
        ),
    ]
