# Generated by Django 3.1.12 on 2023-03-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20230311_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='participants',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
